#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use function cli\line;
use function cli\prompt;

line('Welcome to the Brain Game!');
$name = prompt('May I have your name?');
line("Hello, %s!", $name);

echo "Answer \"yes\" if the number is even, otherwise answer \"no\".\n";
$rightAnswers = 0;

for ($i = 0; $i < 3; $i++) {
    $number = rand(0,15);
    print_r ("Question: {$number}\n");
    $answer = prompt("Your answer");
    $answer = strtolower($answer);
    
    switch ($answer){
        case ($answer !== "yes" && $answer !== "no"):
            if ($number % 2 === 0){
                echo "{$answer} is wrong answer ;( Correct answer was 'yes'.\n";
                echo "Let's try again, {$name}!\n";
                exit();
            } if ($number % 2 !== 0){
                echo "{$answer} is wrong answer ;( Correct answer was 'no'.\n";
                echo "Let's try again, {$name}!\n";
                exit();
            }
            case ($number % 2 === 0 && $answer === 'yes'):
                $rightAnswers += 1;
                echo "Correct!\n";
                
            case ($number % 2 !== 0 && $answer === 'yes'):
                echo "'yes' is wrong answer ;(. Correct answer was 'no'.\n";
                echo "Let's try again, {$name}!'\n";
                exit();

            case ($number % 2 !== 0 && $answer === 'no'):
                $rightAnswers += 1;
                echo "Correct!\n";

            case ($number % 2 === 0 && $answer === 'no'):
                echo "'no' is wrong answer ;(. Correct answer was 'yes'.\n";
                echo "Let's try again, {$name}!\n";
                exit();
            }
break;
}
if ($rightAnswers == 3){
    echo "Congratulations, {$name}!\n";
}
